import React from 'react';
import FigmaButton from './components/FigmaButton';

const FigmaButtonPreview = () => {
  const variants = ['Default', 'Secondary', 'Danger'];
  const sizes = ['Default', 'Small'];
  const states = ['Default', 'Focused', 'Disabled'];

  return (
    <div className="min-h-screen bg-gray-100 p-8 font-sans">
      <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg p-8">
        <header className="mb-8 border-b pb-4">
          <h1 className="text-2xl font-bold text-gray-900">Button Component Preview</h1>
          <p className="text-gray-500 mt-2">Generated from Figma Component Set (node-id: 467-23758)</p>
          <a 
            href="https://www.figma.com/design/4UeHwuFUXx3MydMW5bqvOs/MCP-Apps-for-Claude--Community-?node-id=467-23758" 
            target="_blank" 
            rel="noreferrer"
            className="text-blue-500 hover:text-blue-700 text-sm inline-flex items-center mt-2"
          >
            View in Figma →
          </a>
        </header>

        <div className="space-y-12">
          {variants.map((variant) => (
            <section key={variant} className="space-y-6">
              <h2 className="text-lg font-semibold text-gray-800 border-l-4 border-gray-900 pl-3">
                {variant} Variant
              </h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {sizes.map((size) => (
                  <div key={size} className="bg-gray-50 p-6 rounded-lg border border-gray-200">
                    <h3 className="text-sm font-medium text-gray-500 mb-4 uppercase tracking-wider">
                      {size} Size
                    </h3>
                    
                    <div className="flex flex-wrap gap-4 items-center">
                      {states.map((state) => (
                        <div key={state} className="flex flex-col items-center gap-2">
                          <FigmaButton
                            variant={variant}
                            size={size}
                            state={state}
                            label={state === 'Default' ? 'Button' : state}
                          />
                          <span className="text-xs text-gray-400 font-mono">{state}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </div>

        <footer className="mt-12 pt-8 border-t text-center text-gray-400 text-sm">
          <p>Generated by Trae AI • Based on Figma Design System</p>
        </footer>
      </div>
    </div>
  );
};

export default FigmaButtonPreview;
